### ISSUE TITLE
still work?

### ISSUE THREAD

**Issue by zecao23** [keyiflerolsun/ythls-FastAPI#1]
Does it still work? How can I install it? Thank you

**Comment by keyiflerolsun** [comment]
yes,

just clone repo and `docker compose up -d`

**Comment by zecao23** [comment]
Didn't work for me... gives error 410

**Comment by keyiflerolsun** [comment]
https://ythls.kekikakademi.org/youtube/channel/UCoIUysIrvGxoDw-GkdOGjRw.json

maybe your server ip in blocklist from youtube

**Comment by zecao23** [comment]
> https://ythls.kekikakademi.org/youtube/channel/UCoIUysIrvGxoDw-GkdOGjRw.json
> 
> maybe your server ip in blocklist from youtube

I tested on 3 VPS... Linode, Vultr, and DigitalOcean, and all of them returned a 410 error.

**Comment by keyiflerolsun** [comment]
please you will check in local computer because it is on real ISP network
