### ISSUE TITLE
Veri almıyor

### ISSUE THREAD

**Issue by Teknoist** [keyiflerolsun/ythls-FastAPI#2]
https://ythls.kekikakademi.org/youtube/video/NxpCRpuABsw.m3u8

denediğim zaman video veya canlı yayın için veri almıyor.

**Comment by keyiflerolsun** [comment]
çünkü ilgili video id bir canlı yayına ait değil

**Comment by Teknoist** [comment]
https://www.youtube.com/watch?v=n8mxnQaseP8 -Yayın linki

https://www.youtube.com/@SIHIRLIANNEMKANALDOFFICIAL -Kanal Linki 

Kanal idsi "UC8rnNIpGh8n6ZpWVqOBaKUQ" 

https://ythls.kekikakademi.org/youtube/channel/UC8rnNIpGh8n6ZpWVqOBaKUQ.m3u8

Hocam nerede yanlış yapıyorum ben çözemedin. Sizim iptv listenizdeki youtube yayınlarıda aynı şeklilde çalışmıyor şuan.

**Comment by keyiflerolsun** [comment]
> https://www.youtube.com/watch?v=n8mxnQaseP8 -Yayın linki

https://ythls.kekikakademi.org/youtube/video/n8mxnQaseP8.m3u8

![Screenshot_2024-09-27-13-38-58-701_com mxtech videoplayer ad](https://github.com/user-attachments/assets/9dd6086c-e646-42f5-837d-e6d9a92fe4fa)

sorun gözükmüyor..

**Comment by Teknoist** [comment]
![image](https://github.com/user-attachments/assets/80029322-2520-4581-88df-193f14e725d2)
![image](https://github.com/user-attachments/assets/71023b9a-8670-4791-a9a4-b327d3964d17)

**Comment by keyiflerolsun** [comment]
https://github.com/user-attachments/assets/afe54eb1-5483-4948-b45b-bf1b6f8b3fa3
