### ISSUE TITLE
Cloudflare block

### ISSUE THREAD

**Issue by pk3011** [keyiflerolsun/ythls-FastAPI#3]
Hi sir, 
I am unable to access your url in INDIA.
KINDLY unblock Indian ip from cloudflare.
Thanks in advance

**Comment by keyiflerolsun** [comment]
Hi,

Thank you for reaching out.

Unfortunately, as the service is running on my personal server at home, I am unable to unblock IPs from regions outside of Turkey for security reasons. I hope you understand that this is to ensure the safety and privacy of the server.

However, you are welcome to host the service on your own server or setup, if that is an option for you.

Thanks for your understanding.

**Comment by pk3011** [comment]
Thanks for your reply.
How can host on mine server?
Please guide me.
Thanks a lot in advance.
